### ISSUE TITLE
all: deal with changes in github token permissions

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2154]
I changed the default `GITHUB_TOKEN` permissions. Some actions may stop working. For each action that has issues, we need to modify the YAML file to increase the permissions. For example, CodeQL needs something like:

```YAML
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
```

I think also actions that publish releases are going to be broken.
