### ISSUE TITLE
ooniprobe multi port traceroute confuses protocol when matching send and received packets.

### ISSUE THREAD

**Issue by aagbsn** [ooni/probe#231]
When running the manipulation/traceroute NetTest, for some reason the received packets are incorrectly mixed -- that is, the replies to the udp traceroutes are incorrectly matched with the tcp traceroute.

I took the liberty of santizing the raw packets from the report and adding the destination port to each summary.

Also note that I ran this test with measurement_concurrecy = 1, so there seems to be a bug in that, if each test_ method (scheduled as a measurement) should have completed prior to launching the next, then we wouldn't expect to see the responses get mixed at all.

```
###########################################
# OONI Probe Report for multi_protocol_traceroute_test (0.2)
# Wed Oct 16 19:22:49 2013
###########################################

---
input_hashes: []
options: [-t, '30']
probe_asn: AS1234
probe_cc: ??
probe_ip: 127.0.0.1
software_name: ooniprobe
software_version: 1.0.0-rc3
start_time: ****
test_name: multi_protocol_traceroute_test
test_version: '0.2'
...

---
answer_flags: [ipsrc]
answered_packets: [SANITIZED]

input: null
max_ttl: 30
sent_packets:
summary: IP / TCP 127.0.0.1:43880 > 8.8.8.8:0 S
summary: IP / TCP 127.0.0.1:34914 > 8.8.8.8:telnet S
summary: IP / TCP 127.0.0.1:6033 > 8.8.8.8:ssh S
summary: IP / TCP 127.0.0.1:19253 > 8.8.8.8:domain S
```

Another note, as you can see, we didn't even send packets to all of the ports that we were supposed to! Note that the TCP traceroute is missing information from ports 80, 443, 65535.

```
summary: IP / UDP 127.0.0.1:12126 > 8.8.8.8:0
summary: IP / UDP 127.0.0.1:58010 > 8.8.8.8:23
summary: IP / UDP 127.0.0.1:9801 > 8.8.8.8:ssh
summary: IP / UDP 127.0.0.1:31524 > 8.8.8.8:http
summary: IP / UDP 127.0.0.1:51034 > 8.8.8.8:domain
summary: IP / UDP 127.0.0.1:17738 > 8.8.8.8:65535
summary: IP / ICMP 127.0.0.1 > 8.8.8.8 echo-request 0

```

ICMP traceroute seems to work fine. This makes me think we have a bug with correctly matching packets (perhaps because scapy doesn't properly parse the ICMP error? We should be able to extract the first 64 bits of the original packet from the ICMP payload and match the original packet. I thought that was how this is supposed to work (so why doesn't it?)

```
test_icmp_traceroute:
  hops:
  - {address: 192.168.1.1, rtt: 0.0045909881591796875, ttl: 1}
  - {address: snip, rtt: 0.07092499732971191, ttl: 2}
  - {address: snip, rtt: 0.07577109336853027, ttl: 3}
  - {address: snip, rtt: 0.08469009399414062, ttl: 4}
  - {address: snip, rtt: 0.0893259048461914, ttl: 5}
  - {address: snip, rtt: 0.11208295822143555, ttl: 6}
  - {address: snip, rtt: 0.1211690902709961, ttl: 7}
  - {address: snip, rtt: 0.1256089210510254, ttl: 8}
  - {address: snip, rtt: 0.13081789016723633, ttl: 9}
  - {address: 8.8.8.8, rtt: 0.1351919174194336, ttl: 10}
  .. snip ..
  - {address: 8.8.8.8, rtt: 0.23688197135925293, ttl: 29}
test_tcp_traceroute:
  hops_0:
  - {address: 192.168.1.1, dport: 0, rtt: 0.07303094863891602, sport: 43880, ttl: 1}
  - {address: ****, dport: 0, rtt: 0.10873293876647949, sport: 43880, ttl: 2}
  - {address: ****, dport: 0, rtt: 0.11548089981079102, sport: 43880, ttl: 3}
  - {address: ****, dport: 0, rtt: 0.12311577796936035, sport: 43880, ttl: 4}
  - {address: ****, dport: 0, rtt: 0.1280210018157959, sport: 43880, ttl: 5}
```

Oh, what's this?

```
  - {address: 192.168.1.1, dport: 0, rtt: 0.005198001861572266, sport: 12126, ttl: 1}
  - {address: ****, dport: 0, rtt: 0.11051487922668457, sport: 12126, ttl: 2}
  - {address: ****, dport: 0, rtt: 0.11498403549194336, sport: 12126, ttl: 3}
  - {address: ****, dport: 0, rtt: 0.1281900405883789, sport: 12126, ttl: 4}
  - {address: ****, dport: 0, rtt: 0.12834596633911133, sport: 12126, ttl: 5}
```

missing. (filtered? or?)

```
  hops_123: []
  hops_22:
  - {address: 192.168.1.1, dport: 22, rtt: 0.006288051605224609, sport: 6033, ttl: 1}
  - {address: ****, dport: 22, rtt: 0.03064894676208496, sport: 6033, ttl: 2}
  - {address: ****, dport: 22, rtt: 0.031304121017456055, sport: 6033, ttl: 3}
  - {address: ****, dport: 22, rtt: 0.03136110305786133, sport: 6033, ttl: 4}
  - {address: ****, dport: 22, rtt: 0.03139805793762207, sport: 6033, ttl: 5}
```

That's right, source port 9801 corresponds to the UDP probes we sent. But here they are in the tcp section of the report...

```
  - {address: 192.168.1.1, dport: 22, rtt: 0.005806922912597656, sport: 9801, ttl: 1}
  - {address: ****, dport: 22, rtt: 0.20049190521240234, sport: 9801, ttl: 2}
  - {address: ****, dport: 22, rtt: 0.2050490379333496, sport: 9801, ttl: 3}
  - {address: ****, dport: 22, rtt: 0.20534992218017578, sport: 9801, ttl: 4}
  - {address: ****, dport: 22, rtt: 0.20585894584655762, sport: 9801, ttl: 5}
  hops_23:
  - {address: 192.168.1.1, dport: 23, rtt: 0.00814509391784668, sport: 34914, ttl: 1}
  - {address: ****, dport: 23, rtt: 0.0739450454711914, sport: 34914, ttl: 2}
  - {address: ****, dport: 23, rtt: 0.0788578987121582, sport: 34914, ttl: 3}
  - {address: ****, dport: 23, rtt: 0.10832500457763672, sport: 34914, ttl: 4}
  - {address: ****, dport: 23, rtt: 0.1085820198059082, sport: 34914, ttl: 5}
```

Same pattern

```
  - {address: 192.168.1.1, dport: 23, rtt: 0.0056650638580322266, sport: 58010, ttl: 1}
  - {address: ****, dport: 23, rtt: 0.21145319938659668, sport: 58010, ttl: 2}
  - {address: ****, dport: 23, rtt: 0.21573805809020996, sport: 58010, ttl: 3}
  - {address: ****, dport: 23, rtt: 0.22488021850585938, sport: 58010,
    ttl: 4}
  - {address: ****, dport: 23, rtt: 0.22522902488708496, sport: 58010, ttl: 5}
  hops_443: []
  hops_53:
  - {address: 192.168.1.1, dport: 53, rtt: 0.008939981460571289, sport: 19253, ttl: 1}
  - {address: ****, dport: 53, rtt: 0.033080101013183594, sport: 19253, ttl: 2}
  - {address: ****, dport: 53, rtt: 0.033460140228271484, sport: 19253, ttl: 3}
  - {address: ****, dport: 53, rtt: 0.03826403617858887, sport: 19253, ttl: 4}
  - {address: ****, dport: 53, rtt: 0.04162907600402832, sport: 19253,
    ttl: 5}
  - {address: ****, dport: 53, rtt: 0.06583595275878906, sport: 19253, ttl: 6}
  - {address: ****, dport: 53, rtt: 0.06605195999145508, sport: 19253, ttl: 7}
  - {address: ****, dport: 53, rtt: 0.07021808624267578, sport: 19253, ttl: 8}
  - {address: ****, dport: 53, rtt: 0.07120800018310547, sport: 19253, ttl: 9}
  - {address: 8.8.8.8, dport: 53, rtt: 0.08790111541748047, sport: 19253, ttl: 10}
  - {address: 8.8.8.8, dport: 53, rtt: 0.08807492256164551, sport: 19253, ttl: 11}
  - {address: 8.8.8.8, dport: 53, rtt: 0.09258008003234863, sport: 19253, ttl: 12}
```

See what I mean? What's also kind of odd is that the rtt actually seems correct, I mean, if it were matching the wrong packet you would expect the times to be way off.

```
  - {address: 192.168.1.1, dport: 53, rtt: 0.011338949203491211, sport: 51034, ttl: 1}
  - {address: ****, dport: 53, rtt: 0.25679802894592285, sport: 51034, ttl: 2}
  - {address: ****, dport: 53, rtt: 0.2617018222808838, sport: 51034, ttl: 3}
  - {address: ****, dport: 53, rtt: 0.2659640312194824, sport: 51034, ttl: 4}
  hops_65535:
  - {address: ****, dport: 65535, rtt: 0.23224091529846191, sport: 17738,
    ttl: 1}
  - {address: ****, dport: 65535, rtt: 0.23660492897033691, sport: 17738,
    ttl: 2}
  - {address: ****, dport: 65535, rtt: 0.2581050395965576, sport: 17738, ttl: 3}
  - {address: ****, dport: 65535, rtt: 0.2581288814544678, sport: 17738,
    ttl: 4}
  hops_80:
  - {address: 192.168.1.1, dport: 80, rtt: 0.008314847946166992, sport: 31524, ttl: 1}
```

Why did we only send 1 packet?

```
  hops_8080: []
test_udp_traceroute:
```

We have an explanation for where some of these went, but it would seem we didn't send/match all the packets. Did we lose them?

```
  hops_0: []
  hops_123: []
  hops_22: []
  hops_23: []
  hops_443: []
  hops_53: []
  hops_65535: []
  hops_80: []
  hops_8080: []
timeout: 30
...

```
