### ISSUE TITLE
how to view 127.0.0.1:8842 in tor browser ?

### ISSUE THREAD

**Issue by shirishag75** [ooni/probe#603]
I see in .ooni/ooniprobe.conf and see the following -

```
┌─[shirish@debian] - [~/.ooni] - [10501]
└─[$] cat ooniprobe.conf | tail -14 

tor:
    #socks_port: 8801
    #control_port: 8802
    # Specify the absolute path to the Tor bridges to use for testing
    #bridges: bridges.list
    # Specify path of the tor datadirectory.
    # This should be set to something to avoid having Tor download each time
    # the descriptors and consensus data.
    # data_dir: ~/.tor/
    torrc:
        #HTTPProxy: host:port
        #HTTPProxyAuthenticator: user:password
        #HTTPSProxy: host:port
        #HTTPSProxyAuthenticator: user:password
```

Now I changed some of it to -

```
┌─[shirish@debian] - [~/.ooni] - [10501]
└─[$] cat ooniprobe.conf | tail -14                                                                                                   
tor:
    socks_port: 8801
    control_port: 8802
    # Specify the absolute path to the Tor bridges to use for testing
    #bridges: bridges.list
    # Specify path of the tor datadirectory.
    # This should be set to something to avoid having Tor download each time
    # the descriptors and consensus data.
    data_dir: ~/.tor/
    torrc:
        #HTTPProxy: host:port
        #HTTPProxyAuthenticator: user:password
        #HTTPSProxy: host:port
        #HTTPSProxyAuthenticator: user:password
```

The difference is I just uncommented the default socks and control port as well as data dir . Apart from that all is same. I didn't change anything in the torrc as I do not know if something needs to be changed or not, and if yes, how to know what to change. 

I did run ooniprobe-agent and as can be seen it is running -

```
[$] ooniprobe-agent status

ooniprobe-agent is running
```

But unable to see http://127.0.0.1:8842 on torbrowser which has been running from before the virtualenv activation.
